### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by skimask9** [WTFox/jellybeans.nvim#1]
Would it be possible to add alpha highlights?

**Comment by WTFox** [comment]
Yep! Give me a couple days since it's the holiday and I'll have it out soon.

**Comment by skimask9** [comment]
Thx, I apologize for interrupting you, have a nice holiday

> Yep! Give me a couple days since it's the holiday and I'll have it out soon.

**Comment by WTFox** [comment]
Not a problem at all. You too!

**Comment by WTFox** [comment]
@skimask9 update and try it out.

![image](https://github.com/user-attachments/assets/36764bf7-fe96-4628-b227-e0d6c76e95e2)

**Comment by skimask9** [comment]
@WTFox 
Unfortunately, it's not working for me
![image](https://github.com/user-attachments/assets/42daaef7-75a7-4cec-975d-151c7653a2a1)
![image](https://github.com/user-attachments/assets/96e71d56-29a5-4de8-882f-39287d46e873)

**Comment by WTFox** [comment]
> @WTFox Unfortunately, it's not working for me ![image](https://private-user-images.githubusercontent.com/88349133/391364866-42daaef7-75a7-4cec-975d-151c7653a2a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTA0NTIsIm5iZiI6MTczMzA5MDE1MiwicGF0aCI6Ii84ODM0OTEzMy8zOTEzNjQ4NjYtNDJkYWFlZjctNzVhNy00Y2VjLTk3NWQtMTUxYzc2NTNhMmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDIxNTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmNiNmExMmRjYzdhMGFlNTg2YzMyNzI1NjhmNjA1MmRkNGU2YzQzMmZmZGMyZDE1MGQ5ZWMwYWEwZjIwNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BhyBTMt6BMhYLdANFrZXWQ_e8ApwLX9Xu-1AGHoFQO0) ![image](https://private-user-images.githubusercontent.com/88349133/391364868-96e71d56-29a5-4de8-882f-39287d46e873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwOTA0NTIsIm5iZiI6MTczMzA5MDE1MiwicGF0aCI6Ii84ODM0OTEzMy8zOTEzNjQ4NjgtOTZlNzFkNTYtMjlhNS00ZGU4LTg4MmYtMzkyODdkNDZlODczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDIxNTU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTU2MjViMmQ2Y2Y2MDAwYmI3NjE1MTA4YWNhNWMwMzE2NWIzMWQzNzhkYzcxZDk4ODk1YmRhZTQyNWQ2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EejzMhuhcyRYuI2xqtT0GD9mOmRN_sDB4w4gA9bIw2w)

Interesting because I see the correct highlights being applied in the telescope. I'm using the latest version of alpha. I wonder if there's a cache that didn't clear somewhere.
